version: '3'

services:
  bank-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: waelmorgan/bank-server:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/bsa?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345678
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: bsa
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
